### ISSUE TITLE
ARGB + AARRGGBB option

### ISSUE THREAD

**Issue by nathanwaters** [BananaAcid/hex-and-rgba#1]
For some reason an API I'm currently using takes 8-digit HEX codes in the form of either:

- RGB
- ARGB
- RRGGBB
- AARRGGBB

Just a feature suggestion :)

**Comment by BananaAcid** [comment]
These A* versions are weird :)
Have any info on where/why that is used? [Google suggests android](https://developer.android.com/guide/topics/resources/more-resources.html#Color). (*A is used on windows and web)

**Comment by BananaAcid** [comment]
Added 2 functions: `rgba to aHex` and `aHex to rgba`. As well as the command line scripts.

**Comment by nathanwaters** [comment]
Thankyou! Yeah it's annoying. This is the API I came across it: https://docs.imgix.com/apis/url
